language: java

sudo: false

install: true

jdk: oraclejdk8

script: mvn test

      
notifications:
  email:
    recipients:
    - qureshm@tcd.ie
    - erlist@tcd.ie
    - eozoani@tcd.ie
    - muganc@tcd.ie
    - crawford@tcd.ie
    on_success: always
    on_failure: always 
    
    
    
cache: bundler
